### ISSUE TITLE
Error: decoded.map is not a function

### ISSUE THREAD

**Issue by walshie4** [googleapis/nodejs-spanner#198]
#### Environment details

  - OS: CoreOS
  - Node.js version: v8.9.4
  - npm version: v6.0.1
  - `@google-cloud/spanner` version: v1.4.1

#### Steps to reproduce

  1. ???
  2. ???

This error is occasionally happening when running the same query as in #197.  

```sql
SELECT * FROM <TABLE> ORDER BY id LIMIT 10000 OFFSET @offset
```
```javascript
const [rows] = await spannerDb.run({
  sql: 'SELECT * FROM <table> ORDER BY id LIMIT @limit OFFSET @offset',
  params: {
    limit: 10000,
    offset: 0,
  },
}, { readTimestamp: timestampBound });
return rows.map(row => row.toJSON()); // Causes error from scrambled data
```

```
TypeError: decoded.map is not a function

        at decodeValue_ (/opt/app/node_modules/@google-cloud/spanner/src/codec.js:145)
        at Object.decode (/opt/app/node_modules/@google-cloud/spanner/src/codec.js:179)
        at (/opt/app/node_modules/@google-cloud/spanner/src/partial-result-stream.js:183)
        at Array.map (<anonymous>)
        at Function.partialResultStream.formatRow_ (partial-result-stream.js:179)
        at (/opt/app/node_modules/@google-cloud/spanner/src/partial-result-stream.js:175)
        at Array.map (<anonymous>)
        at Function.partialResultStream.formatRow_ (partial-result-stream.js:173)
        at DestroyableTransform._transform (/opt/app/node_modules/@google-cloud/spanner/src/partial-result-stream.js:99)
        at DestroyableTransform.Transform._read (_stream_transform.js:184)
        at DestroyableTransform.Transform._write (_stream_transform.js:172)

```

**Comment by stephenplusplus** [comment]
This is likely #180 as well, sadly.

**Comment by walshie4** [comment]
Re-opening this following the discussion in #180.  The issue is currently resulting in an unhandled rejection with the above error which seems to cause the promise from the library to never resolve or reject causing our tasks to freeze up.

**Comment by crwilcox** [comment]
@walshie4 
Sorry for a bit of delay between responses. I have rewritten the core logic of how we stream rows. It is possible it has fixed this issue also now (even though I believe this is not related to the other). If you want to try `npm install googleapis/nodejs-spanner#rewrite-partial-result-stream` you can.

**Comment by walshie4** [comment]
🙇 Thank you for the branch @crwilcox.  I've tested it next to my current latest and can confirm it does in fact resolve this issue.

**Comment by crwilcox** [comment]
Quick Update: We are still testing this branch and handling a few edge cases.

**Comment by crwilcox** [comment]
Branch has been updated as we have corrected some corner cases that regressed. As soon as we finish authoring some new tests this fix will be merged.

**Comment by crwilcox** [comment]
A patch release is published that includes this fix. https://www.npmjs.com/package/@google-cloud/spanner

**Comment by sourcec0de** [comment]
@crwilcox I am still encountering this exact same issue using 1.5.0.

**Comment by stephenplusplus** [comment]
@sourcec0de Thanks for reporting. Do you have any code, and/or information about the data and query, that we could use to try to reproduce?

**Comment by sourcec0de** [comment]
@stephenplusplus I have been banging my head on the wall trying to resolve this issue for a few days. I honestly thought it may have been a conflict with other installations of `@google-cloud/*` libraries.

I've been using `babel-node` to take advantage of module's until node supports it out of the box.
After installing and upgrading all my `@google-cloud` libraries I found out that `babel-node` was the issue all along.

Switching to `ts-node` instead eliminated the issue.

Should have waited a little longer before reporting.

Thank you for being so prompt, though. It's great to see you guys active in here.
