### ISSUE TITLE
Session not found error still happens

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-spanner#387]
_From @voltrue2 on October 18, 2018 1:53_

#### Environment details

  - OS: CentOS 
  - Node.js version: 8.x
  - npm version: 6.x
  - google-cloud-node version: 1.4.1

#### Steps to Reproduce

1. Keep connections open for more then an hour.

Hello 

We are still seeing this exact error. It seems to happen every one hour so it really fits the definition given here.
We create each connection with keepAlive option, but it does not seem to be working.
The version of the library we are using is 1.4.1
We are updating it to 2.0.0 in the near future but any help with is error will be appreciated.

Issue related: #2061 

Thanks

_Copied from original issue: googleapis/google-cloud-node#2874_

**Comment by voltrue2** [comment]
Hello,

Here is the log that I see when this error happens:

```
{ message: 'InvalidRowToUpdate',
 type: '5 NOT_FOUND: Session not found: projects/gcp-cobra/instances/bakumon-prd/databases/bakumon/sessions/AFIfEfp_FzdGvc6R1r9PAR_z2p1S3m2SteDm7OXtmPVxY1zJUaGTCql2nSau',
 code: 5 }
```

It seems that one of the session is dead but still kept in the pool somehow. I have seen this issue being talked about here and there for a while, but the issue still remains. Could you guys really have a look at this? It is now affecting our service.

Thanks

**Comment by callmehiphop** [comment]
hey @voltrue2 what are you setting the `keepAlive` option to? After 1 hour the sessions automatically expire.

**Comment by voltrue2** [comment]
@callmehiphop, I am setting 5 to keepAlive which I understand it to ping Spanner server every 5 minutes:

var spanner = new Spanner({ keepAlive: 5 });

**Comment by callmehiphop** [comment]
@voltrue2 In your example, you're passing the pool options to instance method, is that a typo? The correct usage would look like this

```js
var spanner = new Spanner();
var instance = spanner.instance(instanceId);
var database = instance.database(databaseId, {keepAlive: 5});
```

> Another infomation on this is that when the problem happens, it is always the same session.

What do you mean by the same session? Is that to say every time this error occurs the session ID is always the same?

**Comment by voltrue2** [comment]
@callmehiphop Hello, Thanks for the response!

I actually that was the way I thought it was to set keep alive. I will correct my code. It is most likely caused by me setting the keep alive option incorrectly.

While I am at it, is there other options that I need to setting besides `keepAlive`? The documentation does not provide much information of options and such including keep alive. I had to Google search and read a while bunch of threads elsewhere.

Cheers!

**Comment by callmehiphop** [comment]
@voltrue2 [here](https://cloud.google.com/nodejs/docs/reference/spanner/2.1.x/global#SessionPoolOptions) is a list with all the available pooling options.

**Comment by voltrue2** [comment]
Awesome! Thank you.

**Comment by callmehiphop** [comment]
@voltrue2 any updates here? Did this resolve the issue you were seeing??

**Comment by voltrue2** [comment]
@callmehiphop We deployed the updated the update to one of the projects and it has been a week and so far I have not heard any issues of the sessions.
I assume the issue has been resolved.
Thank you for the help!

**Comment by callmehiphop** [comment]
@voltrue2 excellent, glad to hear it!

**Comment by axot** [comment]
I found this error still happening in our production. We also have `keepAlive`, like

```
var database = instance.database(databaseId, {keepAlive: 5});
```

> [2019/08/03 09:48:17:722][WORKER:15591 1]<error>[HTTP.response] Error response: { message: 'InvalidRowToUpdate',
  type: '5 NOT_FOUND: Session not found: projects/xxx/instances/yyy-prd/databases/xxx/sessions/AJSwhARtCybNvJ2rQr7byIJjEfCGfY55aIgksgnQhT8WUVoTd9GCHU9A7MrD',
  code: 5 } 500  (url:GET /app/v1/zzz/ooo/f2e1f7a1-18ae-4f77-9a7f-4021e7d8d0f2/total) (id:bbb)

So maybe we could just catch the exception when sessions is gone, then we create a new one?

**Comment by axot** [comment]
@callmehiphop any ideas?

**Comment by callmehiphop** [comment]
@axot usually if we fail to ping a session we discard it entirely. I am a little surprised to see you would run into this issue with a 5 minute keep alive since sessions only need to be pinged once an hour. 

I think we'll need a little more information like

1. What version of Spanner are you using?
1. When does this error occur? (During a query, randomly via `database.on('error', err => {});`, etc.
1. How many sessions is the database configured to create?

**Comment by axot** [comment]
@callmehiphop 
> What version of Spanner are you using?

2.1.0

> When does this error occur? (During a query, randomly via database.on('error', err => {});, etc.

I think it was happening during a query, but I'm not sure about it, the error log did not include backtrace in this case.

> How many sessions is the database configured to create?

We are using the default values.

**Comment by callmehiphop** [comment]
@axot would you be willing to update to the latest version (v4.0.1) and let me know if the error occurs there as well?

**Comment by axot** [comment]
Sure, because this error happens every month, the next feedback will be much later.
